package com.appliedrec

object VerIDDependencies {

    const val RXJAVA = "io.reactivex.rxjava3:rxjava:[3.0.4,4.0["
    const val RXANDROID = "io.reactivex.rxjava3:rxandroid:[3.0,4.0["
    const val VERID_IDENTITY = "com.appliedrec.verid:identity:[1.1.1,2.0["
    const val APPCOMPAT = "androidx.appcompat:appcompat:[1.3.1,2.0.0["
    const val EXIFINTERFACE = "androidx.exifinterface:exifinterface:[1.1.0,2.0.0["
    const val ROOM_RUNTIME = "androidx.room:room-runtime:[2.2.0,3.0.0["
    const val ROOM_TESTING = "androidx.room:room-testing:[2.2.0,3.0.0["
    const val ROOM_COMPILER = "androidx.room:room-compiler:[2.2.0,3.0.0["
    const val ANNOTATION = "androidx.annotation:annotation:1.1.0"
    const val GSON = "com.google.code.gson:gson:[2.8.5,3.0.0["
    const val CONSTRAINTLAYOUT = "androidx.constraintlayout:constraintlayout:[2.0.4,3.0.0["
    const val DYNAMICANIMATION = "androidx.dynamicanimation:dynamicanimation:[1.0.0,2.0.0["
    const val COMPOSE_UI = "androidx.compose.ui:ui:[1.3.1,2.0.0["
    const val COMPOSE_RUNTIME_LIVEDATA = "androidx.compose.runtime:runtime-livedata:[1.3.1,2.0.0["
    const val COMPOSE_MATERIAL3 = "androidx.compose.material3:material3:1.1.0-alpha02"
    const val COMPOSE_LIFECYCLE_VIEWMODEL = "androidx.lifecycle:lifecycle-viewmodel-compose:2.5.1"
    const val COMPOSE_TOOLING_PREVIEW = "androidx.compose.ui:ui-tooling-preview:1.3.1"
    const val COMPOSE_RUNTIME = "androidx.compose.runtime:runtime:1.3.3"
    const val DESUGAR_JDK_LIBS = "com.android.tools:desugar_jdk_libs:1.0.9"
    const val LIFECYCLE_COMMON_JAVA8 = "androidx.lifecycle:lifecycle-common-java8:[2.2.0,3.0.0["
    const val TEST_JUNIT = "androidx.test.ext:junit:1.1.3"
    const val JUNIT = "junit:junit:4.13.2"
    const val TEST_RUNNER = "androidx.test:runner:1.4.0"
    const val TEST_RULES = "androidx.test:rules:1.4.0"
    const val TEST_MONITOR = "androidx.test:monitor:1.6.0"
    const val ESPRESSO_CORE = "androidx.test.espresso:espresso-core:[3.4.0,4.0.0["
    const val ESPRESSO_INTENTS = "androidx.test.espresso:espresso-intents:[3.4.0,4.0.0["
    const val TEST_ORCHESTRATOR = "androidx.test:orchestrator:1.4.1"
    const val VERID_SERIALIZATION = "com.appliedrec.verid:serialization:1.0.0"
    const val GUAVA = "com.google.guava:guava:30.1.1-android"
    const val PREFERENCE = "androidx.preference:preference:[1.1.1,2.0.0["
    const val PROTOBUF_JAVALITE = "com.google.protobuf:protobuf-javalite:[3.8.0,4["
    const val MULTIDEX = "androidx.multidex:multidex:[2.0.1,3.0.0["
    const val RELINKER = "com.getkeepsafe.relinker:relinker:[1.3.1,2.0.0["
    const val CBOR = "com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:2.11.1"
    const val TENSORFLOW_LITE = "org.tensorflow:tensorflow-lite:2.9.0"
    const val TENSORFLOW_SUPPORT = "org.tensorflow:tensorflow-lite-support:0.4.3"
    const val TENSORFLOW_METADATA = "org.tensorflow:tensorflow-lite-metadata:0.1.0"
    const val TENSORFLOW_TASK_VISION = "org.tensorflow:tensorflow-lite-task-vision:0.4.3"
    const val TENSORFLOW_GPU = "org.tensorflow:tensorflow-lite-gpu:2.9.0"
    const val TENSORFLOW_GPU_DELEGATE = "org.tensorflow:tensorflow-lite-gpu-delegate-plugin:0.4.2"
    const val PYTORCH_ANDROID_LITE = "org.pytorch:pytorch_android_lite:1.12.2"
    const val PYTORCH_ANDROID_TORCHVISION = "org.pytorch:pytorch_android_torchvision_lite:1.12.2"
    const val MOCKITO_CORE = "org.mockito:mockito-core:2.28.2"
    const val MOCKITO_ANDROID = "org.mockito:mockito-android:2.28.2"
}