package com.appliedrec

object VerIDDependencies {

    const val RXJAVA = "io.reactivex.rxjava3:rxjava:3.1.8"
    const val RXANDROID = "io.reactivex.rxjava3:rxandroid:3.0.2"
    const val VERID_IDENTITY = "com.appliedrec.verid:identity:1.1.1"
    const val APPCOMPAT = "androidx.appcompat:appcompat:1.6.1"
    const val EXIFINTERFACE = "androidx.exifinterface:exifinterface:1.3.6"
    const val ROOM_RUNTIME = "androidx.room:room-runtime:2.5.2"
    const val ROOM_TESTING = "androidx.room:room-testing:2.5.2"
    const val ROOM_COMPILER = "androidx.room:room-compiler:2.5.2"
    const val ROOM_KTX = "androidx.room:room-ktx:2.5.2"
    const val ANNOTATION = "androidx.annotation:annotation:1.7.0"
    const val GSON = "com.google.code.gson:gson:2.10.1"
    const val CONSTRAINTLAYOUT = "androidx.constraintlayout:constraintlayout:2.1.0"
    const val DYNAMICANIMATION = "androidx.dynamicanimation:dynamicanimation:1.0.0"
    const val COMPOSE_UI = "androidx.compose.ui:ui:1.4.1"
    const val COMPOSE_RUNTIME_LIVEDATA = "androidx.compose.runtime:runtime-livedata:1.4.1"
    const val COMPOSE_MATERIAL3 = "androidx.compose.material3:material3:1.1.2"
    const val COMPOSE_LIFECYCLE_VIEWMODEL = "androidx.lifecycle:lifecycle-viewmodel-compose:2.6.2"
    const val COMPOSE_TOOLING_PREVIEW = "androidx.compose.ui:ui-tooling-preview:1.4.1"
    const val COMPOSE_RUNTIME = "androidx.compose.runtime:runtime:1.4.1"
    const val DESUGAR_JDK_LIBS = "com.android.tools:desugar_jdk_libs:1.1.5"
    const val LIFECYCLE_COMMON_JAVA8 = "androidx.lifecycle:lifecycle-common-java8:2.6.2"
    const val LIFECYCLE_LIVEDATA_CORE = "androidx.lifecycle:lifecycle-livedata-core:2.6.2"
    const val TEST_JUNIT = "androidx.test.ext:junit:1.1.3"
    const val JUNIT = "junit:junit:4.13.2"
    const val TEST_RUNNER = "androidx.test:runner:1.4.0"
    const val TEST_RULES = "androidx.test:rules:1.4.0"
    const val TEST_MONITOR = "androidx.test:monitor:1.6.0"
    const val ESPRESSO_CORE = "androidx.test.espresso:espresso-core:3.5.0"
    const val ESPRESSO_INTENTS = "androidx.test.espresso:espresso-intents:3.5.0"
    const val TEST_ORCHESTRATOR = "androidx.test:orchestrator:1.4.1"
    const val VERID_SERIALIZATION = "com.appliedrec.verid:serialization:1.0.0"
    const val GUAVA = "com.google.guava:guava:32.1.3-android"
    const val PREFERENCE = "androidx.preference:preference:1.2.1"
    const val PROTOBUF_JAVALITE = "com.google.protobuf:protobuf-javalite:3.24.4"
    const val MULTIDEX = "androidx.multidex:multidex:2.0.1"
    const val RELINKER = "com.getkeepsafe.relinker:relinker:1.4.4"
    const val CBOR = "com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:2.11.1"
    const val MOCKITO_CORE = "org.mockito:mockito-core:2.28.2"
    const val MOCKITO_ANDROID = "org.mockito:mockito-android:2.28.2"
    const val LIVENESS_DETECTION = "com.appliedrec.verid.livenessdetection:common:1.0.0"
    const val SPOOF_DEVICE_DETECTION = "com.appliedrec.verid.livenessdetection:spoof-device-detection:1.0.0"
    const val SPOOF_DEVICE_DETECTION_MODELS = "com.appliedrec.verid.livenessdetection:spoof-device-detection-models:1.0.0"
    const val ANDROIDX_COLLECTION = "androidx.collection:collection:1.2.0"
    const val ANDROIDX_CORE = "androidx.core:core:1.10.0"
    const val KT_COROUTINES_JVM = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:1.7.2"
    const val WORK_RUNTIME = "androidx.work:work-runtime:2.8.1"
    const val CORE_KTX = "androidx.core:core-ktx:1.10.0"
    const val KOTLIN_STDLIB = "org.jetbrains.kotlin:kotlin-stdlib:1.8.10"
}